accounts/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "password-change/", views.PasswordChangeView.as_view(), name="password-change"
    ),
    path("password-reset/", views.PasswordResetView.as_view(), name="password-reset"),
    path(
        "password-reset-done/",
        views.PasswordResetDoneView.as_view(),
        name="password-reset-done",
    ),
    url(
        r"^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
        views.PasswordResetConfirmView.as_view(),
        name="password-reset-confirm",
    ),
]

appKYP/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.conf.urls import *
import profiles.urls
import accounts.urls
import KYPSamhita.urls, KYPSamhita.views
import financedata.urls
from . import views
admin.autodiscover()
# Personalized admin site settings like title and header
admin.site.site_title = "Appkyp Site Admin"
admin.site.site_header = "Appkyp Administration"

urlpatterns = [
    # path("", views.HomePage.as_view(), name="home"),
    path("", KYPSamhita.views.ListingPage , name="home"),
    path("about/", views.AboutPage.as_view(), name="about"),
    path("users/", include(profiles.urls)),
    path("admin/", admin.site.urls),
    path("", include(accounts.urls)),
    path("governance/",include(KYPSamhita.urls)),
    path("finance/",include(financedata.urls)),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^explorer/', include('explorer.urls')),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

profiles/urls.py
from django.urls import path
from . import views

app_name = "profiles"
urlpatterns = [
    path("me/", views.ShowProfile.as_view(), name="show_self"),
    path("me/edit/", views.EditProfile.as_view(), name="edit_self"),
    path("<slug:slug>/", views.ShowProfile.as_view(), name="show"),
]

templates/_brandname.html
Governance Desk

templates/_homeworkflow.html
<div class="col-md-12">
    <div class="row p-0 p-md-5">
      <div class="col-12 col-md-12 px-3 px-md-5 pt-3 pt-md-5">
        <div class="progress bg-status w-100 overflow-auto" style="height: 3rem;">
          {% for i in proposal_status %}
          {% with proposal.status as cs %}
            {% if not cs == None %}
                {% if i == cs or not i.parent %}
                    {% if not cs in i.cancel_dependency.all %}
                        {% if cs.order >= i.order %}
                            <div class="progress-bar bg-default bg-fin col" style="background-color:{{cs.color}}" title="{{i.name}} complete" role="progressbar"  aria-valuenow="" aria-valuemin="0" aria-valuemax="100">{{i.name}}</div>
                        {% else %}
                            <div class="progress-bar bg-default font-primary col" title="{{i.name}} status" role="progressbar"  aria-valuenow="" aria-valuemin="0" aria-valuemax="100">{{i.name}}</div>
                        {% endif %}
                    {% endif %}
                {% endif %}
            {% else %}
                <div class="progress-bar bg-default font-primary col" title="{{i.name}} status" role="progressbar"  aria-valuenow="" aria-valuemin="0" aria-valuemax="100">{{i.name}}</div>
            {% endif %}
          {% endwith %}
          {% endfor %}
        </div> 
      </div>
    </div>
</div>

templates/_internalcost.html
  {% if ic_list.all %}
  <div class="col-md-12">
    <div class="row px-0 px-md-5">
      <div class="col-12 col-md-12 p-3 px-md-5 pb-md-5 pt-md-0">
        <div class="col-12 col-md-12 default-card py-3">
          <div class="row col-12 col-md-12">
            <div class="col-12 col-md-12 px-1 px-md-1">
              <div class="row h-100">
                  <div class="col-12">
                    <span class="h1 pb-0 pb-md-0 text-highlight">Internal Costing</span>
                  </div>
                  <div class="col-12 mt-2 table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th class="border-top-0" scope="col">Internal Entity</th>
                                <th class="border-top-0" scope="col">Item details</th>
                                <th class="border-top-0" scope="col">Category</th>
                                <th class="border-top-0" scope="col">Rate</th>
                                <th class="border-top-0" scope="col">No. of units</th>
                                <th class="border-top-0" scope="col">Unit</th>
                                <th class="border-top-0" scope="col">Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in ic_list.all %}
                            
                            <tr>
                                <td>{{item.entity}}</td>
                                <td>{{item.cost}}</td>
                                <td>{{item.cost_category}}</td>
                                <td>{{item.rate}}</td>
                                <td>{{item.unit}}</td>
                                <td>{{item.nos}}</td>
                                <td>{{item.total_amount}}</td>
                            </tr>

                            {% endfor %}
                        </tbody>
                    </table>
                  </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endif %}

templates/_listworkflow.html
{% load kyp_tags %}
<div class="col-md-12 p-md-0 p-3">
    <div class="row p-0 py-3 p-md-5">
    <div class="col-12 col-md-12 px-0 px-md-3 px-md-0 pt-3 pt-md-0">
        <div class="progress bg-status w-100 overflow-auto" style="height: 3rem;">
        {% with curr_status|get_item:prop.id as cs %}
            {% for i in m_status %}
                {% if not cs == None %}
                    {% if i == cs or not i.parent %}
                        {% if not cs in i.cancel_dependency.all %}
                            {% if cs.order >= i.order %}
                                <div class="progress-bar bg-default bg-fin col" style="background-color:{{cs.color}}" title="{{i.name}} complete" role="progressbar"  aria-valuenow="" aria-valuemin="0" aria-valuemax="100">{{i.name}}</div>
                            {% else %}
                                <div class="progress-bar bg-default font-primary col" title="{{i.name}} status" role="progressbar"  aria-valuenow="" aria-valuemin="0" aria-valuemax="100">{{i.name}}</div>
                            {% endif %}
                        {% endif %}
                    {% endif %}
                {% else %}
                    <div class="progress-bar bg-default font-primary col" title="{{i.name}} status" role="progressbar"  aria-valuenow="" aria-valuemin="0" aria-valuemax="100">{{i.name}}</div>
                {% endif %}
            {% endfor %}
        {% endwith %}
        </div> 
    </div>
    </div>
</div>

templates/_navbar.html
<li {% if active_link == "home" %}class="active"{% endif %}><a href="{% url 'home' %}">Home</a></li>
<li {% if active_link == "about" %}class="active"{% endif %}><a href="{% url 'about' %}">About</a></li>

templates/_oldhomeworkflow.html
<div class="col-md-12">
    <div class="row p-0 p-md-5">
      <div class="col-12 col-md-12 px-3 px-md-5 pt-3 pt-md-5">
        <div class="progress bg-status w-100" style="height: 3rem;">
          {% if kyp_comp == 100 %}
            <div class="progress-bar bg-default start-bar bg-fin" role="progressbar" style="width: 13.5%" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100">KYP complete</div>
          {% else %}
            <div class="progress-bar bg-default start-bar font-primary" title="KYP {{kyp_comp}}% complete" role="progressbar" style="width: 13.5%" aria-valuenow="{{kyp_comp}}" aria-valuemin="0" aria-valuemax="100">KYP pending</div>
          {% endif %}
          {% if prop_sent %}
            <div class="progress-bar bg-default bg-fin" role="progressbar" style="width: 13.5%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"><a href ="{{prop_file.doc.url}}">Proposal sent/received <br/><u>Download</u></a></div>
          {% else %}
            <div class="progress-bar bg-default font-primary" role="progressbar" style="width: 13.5%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">Proposal pending</div>
          {% endif %}
          {% if mou_signed %}
            <div class="progress-bar bg-default bg-fin" role="progressbar" style="width: 19%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"><a href ="{{mou_file.doc.url}}">MoU Signed <br/><u>Download</u></a></div>
          {% else %}
            <div class="progress-bar bg-default font-primary" role="progressbar" style="width: 19%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">MoU pending</div>
          {% endif %}
          {% if projstart %}
            <div class="progress-bar bg-default bg-fin" role="progressbar" style="width: 13.5%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">Partnership Kicked off</div>
          {% else %}
            <div class="progress-bar bg-default font-primary" role="progressbar" style="width: 13.5%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">Kick off pending</div>
          {% endif %}
          {% if projreport %}
            <div class="progress-bar bg-default bg-fin" role="progressbar" style="width: 13.5%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">Project Review</div>
          {% else %}
            <div class="progress-bar bg-default font-primary" role="progressbar" style="width: 13.5%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">Project Review</div>
          {% endif %}
          {% if impactreport %}
            <div class="progress-bar bg-default bg-fin" role="progressbar" style="width: 13.5%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">Impact Review</div>
          {% else %}
            <div class="progress-bar bg-default font-primary" role="progressbar" style="width: 13.5%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">Impact Review</div>
          {% endif %}
          {% if finreview %}
            <div class="progress-bar bg-default end-bar bg-fin" role="progressbar" style="width: 13.5%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">Financial Review</div>
          {% else %}
            <div class="progress-bar bg-default end-bar font-primary" role="progressbar" style="width: 13.5%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">Financial Review</div>
          {% endif %}
        </div> 
      </div>
    </div>
</div>

templates/_oldlistworkflow.html
<div class="col-md-12 p-md-0 p-3">
    <div class="row p-0 py-3 p-md-5">
    <div class="col-12 col-md-12 px-0 px-md-3 px-md-0 pt-3 pt-md-0">
        <div class="progress bg-status w-100" style="height: 3rem;">
        {% for k,v in kyp_comp.items %}
            {% if k == prop.id %}
                {% if v == 100 %}
                    <div class="progress-bar bg-default start-bar bg-fin" role="progressbar" style="width: 13.5%" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100">KYP complete</div>
                {% else %}
                    <div class="progress-bar bg-default start-bar font-primary" title="KYP {{kyp_comp}}% complete" role="progressbar" style="width: 13.5%" aria-valuenow="{{kyp_comp}}" aria-valuemin="0" aria-valuemax="100">KYP pending</div>
                {% endif %}
            {% endif %}
        {% endfor %}
        {% for k,v in prop_file.items %}
            {% if k == prop.id %}
                {% if v.doc %}
                    <div class="progress-bar bg-default bg-fin" role="progressbar" style="width: 13.5%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"><a href ="{{v.doc.url}}">Proposal sent/received <br/><u>Download</u></a></div>
                {% else %}
                    <div class="progress-bar bg-default font-primary" role="progressbar" style="width: 13.5%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">Proposal pending</div>
                {% endif %}
            {% endif %}
        {% endfor %}
        {% for k,v in mou_file.items %}
            {% if k == prop.id %}
                {% if v.doc %}
                    <div class="progress-bar bg-default bg-fin" role="progressbar" style="width: 19%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"><a href ="{{v.doc.url}}">MoU Signed <br/><u>Download</u></a></div>
                {% else %}
                    <div class="progress-bar bg-default font-primary" role="progressbar" style="width: 19%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">MoU pending</div>
                {% endif %}
            {% endif %}
        {% endfor %}
        {% for k,v in projstart_file.items %}
            {% if k == prop.id %}
                {% if v and v.doc %}
                    <div class="progress-bar bg-default bg-fin" role="progressbar" style="width: 13.5%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">Partnership Kicked off</div>
                {% else %}
                    <div class="progress-bar bg-default font-primary" role="progressbar" style="width: 13.5%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">Kick off pending</div>
                {% endif %}
            {% endif %}
        {% endfor %}
        {% for k,v in projreport_file.items %}
            {% if k == prop.id %}
                {% if v and v.doc %}
                    <div class="progress-bar bg-default bg-fin" role="progressbar" style="width: 13.5%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">Project Review</div>
                {% else %}
                    <div class="progress-bar bg-default font-primary" role="progressbar" style="width: 13.5%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">Project Review</div>
                {% endif %}
            {% endif %}
        {% endfor %}
        {% for k,v in impactreport_file.items %}
            {% if k == prop.id %}
                {% if v and v.doc %}
                    <div class="progress-bar bg-default bg-fin" role="progressbar" style="width: 13.5%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">Impact Review</div>
                {% else %}
                    <div class="progress-bar bg-default font-primary" role="progressbar" style="width: 13.5%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">Impact Review</div>
                {% endif %}
            {% endif %}
        {% endfor %}
        {% for k,v in finreview_file.items %}
            {% if k == prop.id %}
                {% if v.doc %}
                    <div class="progress-bar bg-default end-bar bg-fin" role="progressbar" style="width: 13.5%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">Financial Review</div>
                {% else %}
                    <div class="progress-bar bg-default end-bar font-primary" role="progressbar" style="width: 13.5%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">Financial Review</div>
                {% endif %}
            {% endif %}
        {% endfor %}
        </div> 
    </div>
    </div>
</div>

templates/_subsidiarydisbursement.html
  {% if sd_list.all %}  
  <div class="col-md-12">
    <div class="row px-0 px-md-5">
      <div class="col-12 col-md-12 p-3 px-md-5 pt-md-0 pb-md-5">
        <div class="col-12 col-md-12 default-card py-3">
          <div class="row col-12 col-md-12">
            <div class="col-12 col-md-12 px-1 px-md-1">
              <div class="row h-100">
                  <div class="col-12">
                    <span class="h1 pb-0 pb-md-0 text-highlight">Subsidiary Disbursement</span>
                  </div>
                  <div class="col-12 mt-2 table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th class="border-top-0" scope="col">Subsidiary</th>
                                <th class="border-top-0" scope="col">Item details</th>
                                <th class="border-top-0" scope="col">Category</th>
                                <th class="border-top-0" scope="col">Rate</th>
                                <th class="border-top-0" scope="col">No. of units</th>
                                <th class="border-top-0" scope="col">Unit</th>
                                <th class="border-top-0" scope="col">Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in sd_list.all %}
                            
                            <tr>
                                <td>{{item.subsidiary}}</td>
                                <td>{{item.cost}}</td>
                                <td>{{item.cost_category}}</td>
                                <td>{{item.rate}}</td>
                                <td>{{item.unit}}</td>
                                <td>{{item.nos}}</td>
                                <td>{{item.total_amount}}</td>
                            </tr>

                            {% endfor %}
                        </tbody>
                    </table>
                  </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endif %}

templates/about.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}About{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div id="sec1" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>{% include "_brandname.html" %}</h1>
        <p class="lead">An Awesome Tagline Goes Here</p>
      </div>
    </div>
  </div>
</div>

<div id="sec2" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2>Meet The Team</h2>
        <p class="lead">The Wonderful People Behind the Site</p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/9/" alt="profile pic"></div>
        <p class="heavy text-center">Cassidy Coder</p>
        <h2>Front-end developer</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/2/" alt="profile pic"></div>
        <p class="heavy text-center">James King</p>
        <h2>CEO</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/1/" alt="profile pic"></div>
        <p class="heavy text-center">Kate Lamport</p>
        <h2>Front-end designer</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
    </div>
  </div>
</div>

<div id="sec3">
  <div class="container">
    <div class="row">
      <div id="map-outer" class="col-md-12">
        <div id="address" class="col-md-4">
          <h2>Our Location</h2>
          <address>
            <strong>Edge Solutions Ltd.</strong><br>
            Taj Mahal<br>
            Agra<br>
            Uttar Pradesh<br>
            India - 282001<br>
            <abbr>P:</abbr> +91 0562 222 6431
          </address>
        </div>
        <div id="map-container" class="col-md-8"></div>
      </div>
    </div>
  </div>
</div>
{% endblock container %}

{% block scripts %}
  <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <script>

   function init_map() {
     // Enter the latitude and longitude of your office here
	 var myLocation = new google.maps.LatLng(27.176141, 78.042370);

     var mapOptions = {
          center: myLocation,
          zoom: 14
     };

	 var marker = new google.maps.Marker({
	   position: myLocation,
	   title:"We are here"});

     var map = new google.maps.Map(document.getElementById("map-container"),
                                   mapOptions);
	 marker.setMap(map);
   }

   google.maps.event.addDomListener(window, 'load', init_map);
  </script>
{% endblock scripts %}

templates/oldbase.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    {% load thumbnail %}
    
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="author" content="Arun Ravindran">
    <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">

    <title>{% block title %}{% include "_brandname.html" %} :: {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this site -->
    {% block styles %}
    <link href="{% static 'site/css/main.css' %}" rel="stylesheet">
    {% endblock styles %}

    <!-- Custom tags for the head tag -->
    {% block extrahead %}{% endblock extrahead %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    {% block navbar %}
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">
            {% block navbar-brand %}
              <img src="{% static 'site/img/logo.png' %}" alt="logo">
              {% include "_brandname.html" %}
            {% endblock %}
          </a>
        </div>
        {% block navbar-menu %}
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% block navbar-left %}{% endblock %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% block navbar-right %}
              {% if user.is_authenticated %}
                {% if user.is_staff %}
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
                {% endif %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle profile-menu" data-toggle="dropdown">
			<img src="{% thumbnail user.profile.picture|default:'default_profile.png' 30x30 crop %}" alt="" />
			{{ user.get_full_name|truncatechars:20 }}
			<span class="caret"></span>
		    </a>
		    
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'profiles:show_self' %}">Profile</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                  </ul>
                </li>
              {% endif %}
            {% endblock %}
          </ul>
        </div><!--/.nav-collapse -->
        {% endblock %}
    </div>
    {% endblock navbar %}

    {% block messages %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">  <!-- singular -->
            <a class="close" data-dismiss="alert">×</a>
            {{ message|safe }}
          </div>
        {% endfor %}
      {% endif %}
    {% endblock %}

    {% block splash %}
    {% endblock splash %}
    
    {% block container %}
    <div class="container">

      <div class="starter-template">
        <h1>New Project</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div><!-- /.container -->
    {% endblock container %}

    <!-- Site footer -->
    {% block footer %}
      <!-- Some social button for contact will do -->
      <a id="contact"></a>
      <div class="container">
            <div class="footer">
        <div class="row">
          <div class="col-lg-6">
              <p>&copy; Company {% now 'Y' %}</p>
          </div>
          <div class="col-lg-6 text-right">
            Connect with us on
            <a href="#"><i class="fa fa-facebook"></i> Facebook</a> or
            <a href="#"><i class="fa fa-twitter"></i> Twitter</a>
          </div>
        </div>
            </div>
      </div>
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

templates/oldhome.html
{% extends "oldbase.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Home{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="home" %}
{% endblock %}

{% block navbar-right %}
  {% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
<a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
  {% else %}
    {{ block.super }}
  {% endif %}
{% endblock %}

{% block splash %}
  <div class="jumbotron jumbotron-carousel corporate-jumbo">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-sm-8">
          <h1>{% include "_brandname.html" %}</h1>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
	  <a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up for Free!</a>
        </div>
        <div class="col-md-4 col-sm-4">

        </div>
      </div>
    </div>
  </div>
{% endblock splash %}

{% block container %}
<!-- Benefits of the Django application -->
<a id="about"></a>

<div class="container">
  <div class="row">
    <div class="col-lg-4">
      <h2>Heading</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-lg-4">
      <h2>Heading</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-lg-4">
      <h2>Heading</h2>
      <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
      <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
    </div>
  </div>
</div>

{% endblock container %}

{% block scripts %}
<script src="{% static 'site/js/site.js' %}"></script>
{% endblock scripts %}